COMMON_SYMBOLS = {
    "water": "Feeling overwhelmed or symbolizing emotional freedom.",
    "vehicles": "Neutral, but crashes suggest low confidence or stress.",
    "trapped": "Worry about current situation or desire for change.",
    "teeth": "Fear of change or loss of control.",
    "babies": "Desire for family or connecting with inner child.",
    "animals": "Reflects personality traits or instincts.",
    "chased": "Unresolved issues or fear.",
    "death": "Accepting change or new beginnings.",
    "crosses": "Death and rebirth, often for religious individuals.",
    "exams": "Feeling judged or tested in life.",
    "clothing": "Projects identity or self-expression.",
    "food": "Hunger, desires, or nourishment needs.",
    "demons": "Anxiety or negative emotions.",
    "buildings": "Security, safety, or personal foundation.",
    "killing": "Suppressed anger or negative emotions.",
    "money": "Desire for freedom or pleasure.",
    "sex": "Healthy desires or intimacy needs.",
    "falling": "Lack of control or insecurity.",
    "naked": "Fear of embarrassment or vulnerability.",
    "famous": "Desire related to idols or recognition.",
    "cheated": "Past trauma or trust issues.",
    "late": "Fear of missing opportunities.",
    "lost": "Anxiety or lack of direction.",
    "crash": "Worry about future events or failure.",
    "pregnant": "Readiness for new beginnings.",
    "room": "Stagnation or hidden potential.",
    "desire": "Strong personal wants or aspirations.",
    "running": "Feeling stuck or seeking freedom.",
    "flood": "Overwhelmed by emotions.",
    "film": "Brain replaying scenes, often meaningless.",
    "paralysis": "Feeling stuck or in a scary in-between state.",
    "snakes": "Lies, deception, or fear.",
    "spiders": "Fear or feeling trapped.",
    "wasps": "Annoyance or irritation.",
    "dogs": "Happiness or fear, depending on context.",
    "wetting": "Embarrassment or pressure.",
    "flying": "Desire for freedom or escaping constraints.",
    "fire": "Anger, passion, or destruction.",
    "reading": "Thirst for knowledge or learning.",
    "ants": "Annoyance or small stressors.",
    "crying": "Release of repressed emotions.",
    "relative": "Seeking closure or connection.",
    "ex": "Unresolved issues from past relationships.",
    "hiding": "Insecurity or fear of exposure.",
    "burglars": "Insecurity or violation of boundaries.",
    "stabbed": "Fears of betrayal or harm.",
    "shot": "Media-driven fears or vulnerability.",
    "horses": "Desire for freedom or strength.",
    "kissing": "Desire for intimacy or connection.",
    "jumping": "Wanting freedom or taking risks.",
    "kidnapped": "Fear of change or loss of control.",
    "bus": "Lack of control or group journey.",
    "prison": "Rigid rules or anticipation of freedom.",
    "quitting": "Desire for change or escape.",
    "rich": "Desire for freedom or abundance.",
    "drowning": "Losing control or emotional overwhelm.",
    "rollercoaster": "Life’s ups and downs.",
    "tattoo": "Desire to stand out or express identity.",
    "aliens": "Seeking wisdom or feeling out of place.",
    "message": "Waiting for news or communication.",
    "sexual": "Desire for excitement or taboo.",
    "searching": "Unhappiness or readiness for change.",
    "climbing": "Facing challenges or pursuing goals.",
    "love": "Desire for romance or connection.",
    "showering": "Need to cleanse or remove burdens.",
    "invisible": "Desire to avoid attention.",
    "shoe": "Worry about security or foundation.",
    "drugs": "Addiction or health concerns.",
    "sharp": "Difficulty expressing or communication issues.",
    "friend": "Missing connections or nostalgia.",
    "time": "Desire to change or relive moments.",
    "limb": "Fear of losing something important.",
    "forest": "Lack of control or desire for escape.",
    "dark": "Frustration or confusion.",
    "zombies": "Worry about past mistakes.",
    "boss": "Authority figure or control issues.",
    "family": "Relationships or support system.",
    "hair": "Identity or fear of loss.",
    "wedding": "Commitment or new beginnings.",
    "quarrel": "Conflict or unresolved issues.",
    "separation": "Endings or independence.",
    "abyss": "Fear of the unknown or future.",
    "barrier": "Obstacles or limitations.",
    "bathtub": "Cleansing or relaxation needs.",
    "explosion": "Sudden change or emotional release.",
    "garden": "Growth, fertility, or creativity.",
    "key": "Solutions or new opportunities.",
    "mask": "Hiding true self or deception.",
    "pyramid": "Stability or achievement.",
    "smoke": "Confusion or obscured vision.",
    "volcano": "Suppressed emotions or eruption.",
    "scales": "Balance or justice.",
    "magic": "Transformation or mystery.",
    "dwarf": "Feeling small or overlooked.",
    "rejection": "Fear of not being accepted.",
    "departure": "Change or moving on.",
    "absence": "Missing something or someone.",
    "agent": "Intermediary or external influence.",
    "railway": "Life’s journey or path.",
    "farm": "Hard work or productivity.",
    "letter": "Communication or news.",
    "wall": "Protection or boundaries.",
    "cowboy": "Adventure or freedom.",
    "roof": "Shelter or protection.",
    "date": "Time or significant event.",
    "detective": "Seeking truth or investigation.",
    "dream": "Aspirations or unconscious thoughts.",
    "loneliness": "Isolation or need for connection.",
    "mythical": "Fantasy or imagination.",
    "bicycle": "Balance or personal progress.",
    "pen": "Expression or creativity.",
    "wing": "Freedom or transcendence.",
    "cemetery": "Endings or remembrance.",
    "football": "Teamwork or competition.",
    "baggage": "Emotional weight or past issues.",
    "grandmother": "Wisdom or nurturing.",
    "household": "Domestic life or family matters.",
    "witch": "Magic or feminine power.",
    "hygiene": "Cleanliness or health.",
    "interview": "Evaluation or opportunity.",
    "hunting": "Pursuit of goals or desires.",
    "youth": "Vitality or new beginnings.",
    "beetle": "Transformation or resilience.",
    "labyrinth": "Complexity or confusion.",
    "lantern": "Guidance or illumination.",
    "lie": "Deception or untruths.",
    "knife": "Cutting ties or aggression.",
    "mother": "Nurturing or care.",
    "nature": "Connection to environment.",
    "envy": "Jealousy or desire for others’ qualities.",
    "oasis": "Relief or refreshment.",
    "slap": "Shock or wake-up call.",
    "postcard": "Message from afar.",
    "revenge": "Retaliation or unresolved anger.",
    "ruin": "Decay or loss.",
    "sand": "Time passing or instability.",
    "satan": "Evil or temptation.",
    "pain": "Suffering or emotional hurt.",
    "silence": "Peace or repression.",
    "dove": "Peace or love.",
    "grief": "Sorrow or loss.",
    "clock": "Time management or deadlines.",
    "vacation": "Need for rest or escape.",
    "vampire": "Draining energy or exploitation.",
    "despair": "Hopelessness or deep sadness.",
    "accident": "Unexpected events or loss of control.",
    "airplane": "Travel or ambition.",
    "alien": "Feeling out of place or unknown.",
    "angel": "Protection or guidance."
}

def interpret_symbols(tokens, user_context=None):
    found = {}
    for token in tokens:
        if token in COMMON_SYMBOLS:
            found[token] = COMMON_SYMBOLS[token]
    # Optionally enrich with user_context
    if user_context:
        found['user_context'] = user_context
    return found